import { splitMultiline } from "./formatters";

const pageSize = {
  width: 595.28,
  height: 841.89
};

const wrapText = (text, font, fontSize, maxWidth) => {
  const words = text.split(" ");
  const lines = [];
  let currentLine = "";

  words.forEach((word) => {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const testWidth = font.widthOfTextAtSize(testLine, fontSize);

    if (testWidth <= maxWidth || !currentLine) {
      currentLine = testLine;
    } else {
      lines.push(currentLine);
      currentLine = word;
    }
  });

  if (currentLine) {
    lines.push(currentLine);
  }

  return lines;
};

const downloadResumePdf = async (resume) => {
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");
  const pdfDoc = await PDFDocument.create();
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const italicFont = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

  const createPage = (withHeader = false) => {
    const page = pdfDoc.addPage([pageSize.width, pageSize.height]);

    page.drawRectangle({
      x: 0,
      y: 0,
      width: pageSize.width,
      height: pageSize.height,
      color: rgb(0.9725, 0.9804, 0.9882)
    });

    if (withHeader) {
      page.drawRectangle({
        x: 40,
        y: pageSize.height - 132,
        width: 515,
        height: 92,
        color: rgb(0.0588, 0.4627, 0.4314)
      });

      page.drawText(resume.name || "Your Name", {
        x: 58,
        y: pageSize.height - 82,
        size: 24,
        font: boldFont,
        color: rgb(1, 1, 1)
      });

      page.drawText("ATS-friendly resume generated by NextJob Portal", {
        x: 58,
        y: pageSize.height - 110,
        size: 11,
        font: regularFont,
        color: rgb(1, 1, 1)
      });
    }

    return page;
  };

  let page = createPage(true);
  let cursorY = pageSize.height - 170;

  const ensureSpace = (requiredHeight = 42) => {
    if (cursorY >= requiredHeight + 52) {
      return;
    }

    page = createPage(false);
    cursorY = pageSize.height - 64;
  };

  const drawSection = (title, content) => {
    const lines = splitMultiline(content);

    if (!lines.length) {
      return;
    }

    ensureSpace(70);
    page.drawText(title.toUpperCase(), {
      x: 48,
      y: cursorY,
      size: 12,
      font: boldFont,
      color: rgb(0.0588, 0.0902, 0.1647)
    });

    page.drawLine({
      start: { x: 48, y: cursorY - 8 },
      end: { x: 150, y: cursorY - 8 },
      thickness: 1.2,
      color: rgb(0.0588, 0.4627, 0.4314)
    });

    cursorY -= 28;

    lines.forEach((line) => {
      const wrappedLines = wrapText(`- ${line}`, regularFont, 10.5, 500);
      ensureSpace(wrappedLines.length * 16);

      wrappedLines.forEach((wrappedLine) => {
        page.drawText(wrappedLine, {
          x: 48,
          y: cursorY,
          size: 10.5,
          font: regularFont,
          color: rgb(0.2, 0.2549, 0.3333)
        });
        cursorY -= 15;
      });

      cursorY -= 6;
    });

    cursorY -= 8;
  };

  drawSection("Skills", resume.skills);
  drawSection("Education", resume.education);
  drawSection("Experience", resume.experience);
  drawSection("Projects", resume.projects);

  ensureSpace(30);
  page.drawText("Tip: Tailor each section with keywords from the role you are applying for.", {
    x: 48,
    y: cursorY,
    size: 9.5,
    font: italicFont,
    color: rgb(0.3922, 0.4549, 0.5451)
  });

  const pdfBytes = await pdfDoc.save();
  const blob = new Blob([pdfBytes], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `${(resume.name || "resume").toLowerCase().replace(/[^a-z0-9]+/g, "-")}-resume.pdf`;
  link.click();
  URL.revokeObjectURL(url);
};

export default downloadResumePdf;
